steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/raglaw-504706/raglaws:$COMMIT_SHA'
      - '-f'
      - 'api/Dockerfile'
      - '.'
    id: 'build-backend'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/raglaw-504706/raglaws:$COMMIT_SHA']
    id: 'push-backend'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'raglaws'
      - '--image=gcr.io/raglaw-504706/raglaws:$COMMIT_SHA'
      - '--region=asia-southeast1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=8000'
      - '--cpu=2'
      - '--memory=2Gi'
      - '--min-instances=0'
      - '--max-instances=3'
    id: 'deploy-backend'

images:
  - 'gcr.io/raglaw-504706/raglaws:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
